# Build dotnet core project using Azure Pipelines

# build name format
name: WebApp.${Date:yyyyMMdd}.$(Rev:.r)
pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

# trigger CI build for the following branches
trigger: [ dev ]

# disable CI builds for pull requests for now
pr: none

steps:
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: Product/WebApp

- task: DotNetCoreCLI@2
  displayName: Compile
  inputs:
    command: build 
    arguments: --configuration $(buildConfiguration)
    projects: Product/WebApp

- task: DotNetCoreCLI@2
  displayName: Prepare Publish Files
  inputs:
    command: publish
    arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    projects: Product/WebApp

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    artifactName: 'webapp'
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: Deploy to Staging Environment
  inputs:
    azureSubscription: 'Digital BT (933642d7-459a-499f-acc7-0d9a14ecf604)'
    appType: 'webApp'
    WebAppName: 'CareerCircleWebApp'
    Package: '$(System.ArtifactsDirectory)'