# Build dotnet core project using Azure Pipelines

# build name format
name: webapp.$(date:yyyyMMdd)$(rev:.r)
pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

# trigger CI build for the following branches
trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - Product/UpDiddyLib/*
      - Product/WebApp/*
    exclude:
      - Product/API/*

# disable CI builds for pull requests for now
pr: none

steps:
- script: |
    dotnet restore Product/WebApp
  displayName: Restore NuGet Packages

- script: |
    dotnet build Product/WebApp --configuration $(buildConfiguration)
  displayName: Compile

- script: |
    dotnet test Product/UpDiddyLib.Tests --logger trx --results-directory $(Agent.TempDirectory)
  displayName: UpDiddyLib Unit Tests'

- script: |
    dotnet publish Product/WebApp --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish Files

- script: |
    cd $(Build.ArtifactStagingDirectory)
    zip -rm WebApp.zip *
  displayName: Packaging

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    artifactName: 'webapp'